### ISSUE TITLE
TypeError: Cannot create property 'cwd' on string

### ISSUE THREAD

**Issue by ronilaukkarinen** [JustBlackBird/gulp-phpcs#40]
Recently noticed gulp-phpcs starts to run files other than php, be it css or js... so I defined the src better, but then getting:

TypeError: Cannot create property 'cwd' on string 'content/themes/dev/template-parts/*.php'

Here's my task currently:

```` js
gulp.task('phpcs', function() {

  gulp.src(themeDir + '/*.php', themeDir + '/template-parts/*.php', themeDir + '/template-parts/modules/*.php')

    // Validate files using PHP Code Sniffer
    .pipe(phpcs({
      bin: '/usr/local/bin/phpcs',
      standard: themeDir + '/phpcs.xml',
      warningSeverity: 0
    }))

    // Log all problems that was found
    .pipe(phpcs.reporter('log'));
});
````

How to fix?

**Comment by DaveLak** [comment]
This doesn't look like an issue with this project; it looks like you're getting the error because you're incorrectly passing the glob patterns to `gulp.src()` . [Have a look at the docs](https://gulpjs.com/docs/en/api/src), if you want to pass multiple globs, the first argument should be an array of patterns.

As for `gulp-phpcs` processing more than PHP files, I believe that's by design. PHP_CodeSniffer works with PHP, CSS and JS.
